#!/bin/bash
set -o pipefail

SAGERNET_KEY_URL="https://sing-box.app/gpg.key"
SAGERNET_KEYRING="/etc/apt/keyrings/sagernet.asc"
SAGERNET_SOURCES="/etc/apt/sources.list.d/sagernet.sources"
SAGERNET_REPO_URI="https://deb.sagernet.org/"
CONFIG_PATH="/etc/sing-box/config.json"
INFO_PATH="/root/proxy-info.txt"
NODES_DIR="/etc/sing-box/nodes"
CERTS_DIR="/etc/sing-box/certs"
APP_NAME="Leyili"
COMMAND_NAME="sb"
SCRIPT_PATH="/usr/local/bin/${COMMAND_NAME}"
SELF_INSTALL_URL="${SELF_INSTALL_URL:-https://raw.githubusercontent.com/lqlcj/linux-menu/main/leyili.sh}"
TCP_TUNING_PATH="/etc/sysctl.d/99-proxy-optimized.conf"
QUIC_TUNING_PATH="/etc/sysctl.d/99-quic-optimized.conf"
INITCWND_SERVICE_PATH="/etc/systemd/system/initcwnd.service"
INITCWND_VALUE="24"
SWAPFILE_PATH="/swapfile"
SWAP_SYSCTL_PATH="/etc/sysctl.d/99-swap-tuning.conf"
SWAPPINESS_VALUE="10"

# ─── Xray 附加内核（用于 vless-xhttp-reality）────
# 与 sing-box 完全独立：独立 systemd 服务 + 独立配置目录，互不污染
XRAY_DIR="/etc/leyili/xray"
XRAY_CONFIG_PATH="${XRAY_DIR}/config.json"
XRAY_BIN_PATH="/usr/local/bin/xray-leyili"
XRAY_SERVICE_NAME="xray-leyili"
XRAY_SERVICE_PATH="/etc/systemd/system/xray-leyili.service"
XRAY_RELEASE_API="https://api.github.com/repos/XTLS/Xray-core/releases/latest"
XRAY_FALLBACK_VERSION="v26.3.27"
XRAY_INBOUND_TAG="xhttp-reality-in"

REALM_BIN_PATH="/usr/local/bin/realm-bin"
REALM_CONFIG_DIR="/etc/realm"
REALM_CONFIG_PATH="/etc/realm/config.toml"
REALM_SERVICE_PATH="/etc/systemd/system/realm.service"
REALM_DOWNLOAD_BASE="https://github.com/zhboner/realm/releases/latest/download"
SYSTEM_TIMEZONE="Asia/Shanghai"
BASIC_TOOLS_PACKAGES="curl wget git vim htop unzip net-tools"
SSHD_CONFIG_PATH="/etc/ssh/sshd_config"
SUDOERS_DROPIN_DIR="/etc/sudoers.d"
SSH_RANDOM_PORT_MIN="20000"
SSH_RANDOM_PORT_MAX="65535"
IP6_RULES_PATH_DEBIAN="/etc/iptables/rules.v6"
IP6_RULES_PATH_RHEL="/etc/sysconfig/ip6tables"
IP4_RULES_PATH_DEBIAN="/etc/iptables/rules.v4"
IP4_RULES_PATH_RHEL="/etc/sysconfig/iptables"

# ─── WARP 谷歌解锁分流 ───────────────────────────────
WARP_APP_NAME="WARP 谷歌解锁分流"
WARP_DIR="/etc/leyili/warp"
WARP_WGCF_ACCOUNT="${WARP_DIR}/wgcf-account.toml"
WARP_WGCF_PROFILE="${WARP_DIR}/wgcf-profile.conf"
WARP_WGCF_BIN="/usr/local/bin/wgcf"
WARP_WGCF_RELEASE_API="https://api.github.com/repos/ViRb3/wgcf/releases/latest"
WARP_OUTBOUND_TAG="warp-out"
WARP_RULESET_TAG="geosite-google"
WARP_RULESET_URL="https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google.srs"
WARP_PEER_PUBLIC_KEY="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
WARP_ENDPOINT_HOST="162.159.192.1"
WARP_ENDPOINT_PORT="2408"
WARP_MTU="1280"

# ─── 颜色 ────────────────────────────────────────────
G="\033[32m" Y="\033[33m" C="\033[36m" R="\033[31m" B="\033[1m" N="\033[0m"
L="\033[94m" W="\033[97m" D="\033[2m"

# ─── 通用辅助 ────────────────────────────────────────
